name: Go libs

on:
  push:
    branches:
      - main
      - ci-*
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - shared/lib/db
          - shared/lib/logger
          - shared/lib/runutil
    steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.1'
            cache-dependency-path: ${{matrix.dir}}/go.sum

        - name: Test
          run: go test -v ./...
          working-directory: ${{matrix.dir}}

  linter:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - shared/lib/db
          - shared/lib/logger
          - shared/lib/runutil
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.54.2'
          args: --timeout=30m --config=../../../.golangci.pipeline.yaml --issues-exit-code=0
          working-directory: ${{matrix.dir}}
