#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE ${CHAT_DB_NAME};
	CREATE ROLE ${CHAT_DB_USER} WITH LOGIN PASSWORD '${CHAT_DB_PASS}';
	GRANT ALL ON DATABASE ${CHAT_DB_NAME} TO ${CHAT_DB_USER};
	ALTER DATABASE ${CHAT_DB_NAME} OWNER TO ${CHAT_DB_USER};
EOSQL
